### PR TITLE
added runOnDraft config

### PR DESCRIPTION
**Pull request by eranelbaz**
https://github.com/kentaro-m/auto-assign-action/issues/36
enable setting to run on draft pull requests

### CODE REVIEW

**Comment by eranelbaz** [comment]
@kentaro-m Hey, any updates?

**Review by kentaro-m — APPROVED** [review]
Hi, @eranelbaz.
Thanks for adding a new feature to run on draft PR.

**Comment by kentaro-m** [comment]
@eranelbaz 
I released new version of auto-assign-action.
If it’s possible, please check it.
https://github.com/kentaro-m/auto-assign-action/releases/tag/v1.2.0

**Comment by eranelbaz** [comment]
@kentaro-m thanks for the release
checked that and it works

**Pull request merged**
